# Generated by Django 5.1.2 on 2024-10-12 10:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('description', models.TextField(default='Описание отсутствует', verbose_name='Описание категории')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('company', models.CharField(max_length=105, verbose_name='Название компании')),
                ('exp', models.CharField(default='Без опыта', max_length=87, verbose_name='Опыт работы')),
                ('salary', models.CharField(max_length=50, verbose_name='Оклад')),
                ('desc', models.TextField(verbose_name='Описание вакансии')),
                ('skills', models.CharField(max_length=250, verbose_name='Навыки')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=14, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startit_app.category', verbose_name='Выберите категорию')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
