# Generated by Django 5.1.2 on 2024-10-12 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startit_app', '0002_age_chislo_slozhno_strashno_quest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chislo',
            options={'verbose_name': 'Количество', 'verbose_name_plural': 'Количества'},
        ),
        migrations.AlterField(
            model_name='quest',
            name='slozhno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startit_app.slozhno', verbose_name='Выберите сложность'),
        ),
        migrations.AlterField(
            model_name='slozhno',
            name='description',
            field=models.TextField(default='Описание отсутствует', verbose_name='Описание сложности'),
        ),
        migrations.AlterField(
            model_name='slozhno',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название сложности'),
        ),
        migrations.AlterField(
            model_name='strashno',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название сложности'),
        ),
    ]
