# Generated by Django 5.1.2 on 2024-10-12 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startit_app', '0003_alter_chislo_options_alter_quest_slozhno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='chislo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='startit_app.chislo', verbose_name='Выберите количество'),
        ),
        migrations.AlterField(
            model_name='strashno',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название страшности'),
        ),
    ]
