# Generated by Django 5.1.2 on 2024-10-15 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startit_app', '0006_remove_job_category_delete_category_delete_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='addresesQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', models.CharField(default='Контакты', max_length=255, verbose_name='Контакты')),
                ('addres', models.CharField(max_length=255, verbose_name='Название адресса')),
                ('ostanovka', models.CharField(max_length=255, verbose_name='Название остановку')),
                ('phone', models.CharField(max_length=255, verbose_name='Название номер телефона')),
                ('wifi', models.CharField(max_length=55, verbose_name='вай фай')),
                ('parking', models.CharField(max_length=55, verbose_name='Парковка:')),
                ('waitroom', models.CharField(max_length=255, verbose_name='Зона ожидания:')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Парковка:')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Парковка',
                'verbose_name_plural': 'Парковки',
            },
        ),
        migrations.CreateModel(
            name='waitroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Зона ожидания:')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Зона ожидания',
                'verbose_name_plural': 'Зона ожидании',
            },
        ),
        migrations.CreateModel(
            name='Smiths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название квеста')),
                ('description', models.TextField(default='Описание отсутствует', verbose_name='Описание квеста')),
                ('phone', models.CharField(max_length=255, verbose_name='Название номер телефона')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('chislo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startit_app.chislo', verbose_name='Выберите количество')),
                ('slozhno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startit_app.slozhno', verbose_name='Выберите сложность')),
                ('strashno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startit_app.strashno', verbose_name='Выберите страшность')),
            ],
            options={
                'verbose_name': 'Квест',
                'verbose_name_plural': 'Квесты',
            },
        ),
    ]
