# Generated by Django 5.1.2 on 2024-10-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startit_app', '0007_addresesq_parking_waitroom_smiths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresesq',
            name='contacts',
        ),
        migrations.AddField(
            model_name='addresesq',
            name='name',
            field=models.CharField(default='Контакты', max_length=255, verbose_name='Название контакта'),
        ),
    ]
