# Generated by Django 5.1.2 on 2024-10-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startit_app', '0009_addresesq_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='age',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Возраст'),
        ),
    ]
