# Generated by Django 5.1.2 on 2024-10-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startit_app', '0010_alter_age_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresesq',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Номер телефона'),
        ),
    ]
