# Generated by Django 5.1.2 on 2024-10-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startit_app', '0014_addresesq_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smiths',
            options={'verbose_name': 'Квестb', 'verbose_name_plural': 'Квестыb'},
        ),
        migrations.AlterField(
            model_name='smiths',
            name='phone',
            field=models.IntegerField(default='+705 777 7777', verbose_name='Напишите номер'),
        ),
    ]
