# Generated by Django 5.1.2 on 2024-10-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startit_app', '0015_alter_smiths_options_alter_smiths_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresesq',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Вставьте изображение'),
        ),
    ]
