# Generated by Django 5.1.2 on 2024-10-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startit_app', '0016_addresesq_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name='Цена'),
        ),
    ]
