# Generated by Django 5.1.2 on 2024-10-18 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startit_app', '0017_quest_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smiths',
            name='chislo',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='chislo',
        ),
        migrations.DeleteModel(
            name='chislo',
        ),
    ]
