# Generated by Django 5.1.2 on 2024-10-18 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startit_app', '0019_infotxt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infotxt',
            name='info',
        ),
        migrations.AddField(
            model_name='infotxt',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Время создания'),
        ),
        migrations.AddField(
            model_name='infotxt',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='infotxt',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Описание'),
        ),
        migrations.DeleteModel(
            name='Smiths',
        ),
    ]
