# Generated by Django 5.1.2 on 2024-10-31 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startit_app', '0021_addresesq_quest'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile_pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('image_url', models.URLField(blank=True, default='', max_length=500, verbose_name='Вставьте изображение')),
            ],
            options={
                'verbose_name': 'Профиль фотка',
                'verbose_name_plural': 'Профильные фотки',
            },
        ),
        migrations.AlterField(
            model_name='addresesq',
            name='quest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='startit_app.quest', verbose_name='Квест'),
        ),
    ]
