# Generated by Django 5.1.2 on 2024-10-31 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startit_app', '0022_profile_pic_alter_addresesq_quest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_pic',
            old_name='image_url',
            new_name='image_profile_url',
        ),
    ]
