# Generated by Django 5.1.2 on 2024-10-31 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startit_app', '0023_rename_image_url_profile_pic_image_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_pic',
            name='name',
            field=models.CharField(default='Контакты', max_length=255, verbose_name='Название фотки'),
        ),
    ]
