# Generated by Django 5.1.2 on 2024-11-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startit_app', '0025_likedquests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikedQuests',
        ),
    ]
