# Generated by Django 5.1.2 on 2024-11-07 04:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startit_app', '0026_delete_likedquests'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название квеста')),
                ('image_url', models.URLField(blank=True, default='', max_length=500, verbose_name='Вставьте изображение')),
                ('description', models.TextField(default='Описание отсутствует', verbose_name='Описание квеста')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Время создания')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name='Цена')),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startit_app.age', verbose_name='Выберите возраст')),
                ('slozhno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startit_app.slozhno', verbose_name='Выберите сложность')),
                ('strashno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startit_app.strashno', verbose_name='Выберите страшность')),
            ],
            options={
                'verbose_name': 'Квест',
                'verbose_name_plural': 'Квесты',
            },
        ),
    ]
