# Generated by Django 5.1.2 on 2024-11-07 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startit_app', '0027_questprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questprofile',
            options={'verbose_name': 'Квест профиля', 'verbose_name_plural': 'Квесты профиля'},
        ),
    ]
